name: document_scanner
description: A plugin that creates a native platform view that scans documents, as a flutter widget.
version: 1.0.0
homepage: https://github.com/blackpink7/flutter_document_scanner_pro

environment:
  sdk: '>=2.12.0 <3.0.0'
  flutter: ">=1.12.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_plugin_android_lifecycle: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  plugin:
    platforms:
      android:
        package: com.example.document_scanner
        pluginClass: DocumentScannerPlugin
      ios:
        pluginClass: DocumentScannerPlugin
    # androidPackage: com.example.document_scanner
    # pluginClass: DocumentScannerPlugin

  
  
  
  
  
  
  
  
  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
